export const QUERY_KEY_FILE = 'QUERY_KEY_FILE';
export const QUERY_KEY_FILE_STATUS = 'QUERY_KEY_FILE_STATUS';

export const QUERY_KEY_UNLOCK_FILE = 'QUERY_KEY_UNLOCK_FILE';
export const QUERY_KEY_UNLOCK_SYMBOL = 'QUERY_KEY_UNLOCK_SYMBOL';

export const QUERY_KEY_THREADS = 'QUERY_KEY_THREADS';
export const QUERY_KEY_THREADS_COLLECTIONS = 'QUERY_KEY_THREADS_COLLECTIONS';

export const QUERY_KEY_THREAD_INFO = 'QUERY_KEY_THREAD_INFO';
