export const QUERY_KEY_FILE = 'QUERY_KEY_FILE';
export const QUERY_KEY_FILE_STATUS = 'QUERY_KEY_FILE_STATUS';

export const QUERY_KEY_UNLOCK_FILE = 'QUERY_KEY_UNLOCK_FILE';
export const QUERY_KEY_UNLOCK_SYMBOL = 'QUERY_KEY_UNLOCK_SYMBOL';

export const QUERY_KEY_HAS_VALID = 'QUERY_KEY_HAS_VALID';
