export const QUERY_KEY_FILE = 'QUERY_KEY_FILE';
export const QUERY_KEY_FILE_STATUS = 'QUERY_KEY_FILE_STATUS';

export const QUERY_KEY_UNLOCK_FILE = 'QUERY_KEY_UNLOCK_FILE';
export const QUERY_KEY_UNLOCK_SYMBOL = 'QUERY_KEY_UNLOCK_SYMBOL';

export const QUERY_KEY_THREADS = 'QUERY_KEY_THREADS';
export const QUERY_KEY_THREADS_COLLECTIONS = 'QUERY_KEY_THREADS_COLLECTIONS';

export const QUERY_KEY_THREAD_INFO = 'QUERY_KEY_THREAD_INFO';

export const QUERY_KEY_HAS_VALID = 'QUERY_KEY_HAS_VALID';
export const QUERY_KEY_COLLECTION_INFO = 'QUERY_KEY_COLLECTION_INFO';

export const QUERY_KEY_DEVELOPERS_ALL = 'QUERY_KEY_DEVELOPERS_ALL';
export const QUERY_KEY_GAMES_ALL = 'QUERY_KEY_GAMES_ALL';
export const QUERY_KEY_GAMES_PUBLISHED = 'QUERY_KEY_GAMES_PUBLISHED';
export const QUERY_KEY_GAMES_BY_DEVELOPER = 'QUERY_KEY_GAMES_PUBLISHED';

export const QUERY_KEY_OWNED_LOCKS = 'QUERY_KEY_OWNED_LOCKS';
